FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements-api.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-api.txt

COPY app/ ./app/
COPY src/ ./src/
COPY configs/ ./configs/
COPY checkpoints/ ./checkpoints/

CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port $PORT"]